###Creating Single dimensional array

In [1]:
import numpy as np

In [2]:
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

###Creating Multi-Dimensional array

In [5]:
n2 = np.array([[10,20,30,40], [40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [6]:
type(n1), type(n2)

(numpy.ndarray, numpy.ndarray)

###Extracting elements

In [7]:
n1

array([10, 20, 30, 40])

In [8]:
n1[0]

10

In [9]:
n1[1:3]

array([20, 30])

In [10]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [11]:
n2[0]

array([10, 20, 30, 40])

In [12]:
n2[1]

array([40, 30, 20, 10])

In [13]:
n2[:,0]

array([10, 40])

In [14]:
n2[0,0]

10

In [15]:
n2[0,1]

20

In [16]:
n2[1,0]

40

In [18]:
#np.zeros
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [19]:
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#np.arange
n3=np.arange(10, 20)
n3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
n3=np.arange(10, 50, 5)
n3

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
#np.full
n3=np.full((2, 2), 10)
n3

array([[10, 10],
       [10, 10]])

In [25]:
#np.randint
n3 = np.random.randint(1, 100, 5)
n3

array([66,  1, 30, 92, 38])

In [26]:
n3.shape

(5,)

In [27]:
n2.shape

(2, 4)

###NumPy Sum

In [28]:
n1 = np.array([10, 20])
n2 = np.array([30, 40])

np.sum([n1, n2])

100

In [29]:
np.sum([n1, n2], axis=0)

array([40, 60])

In [30]:
np.sum([n1, n2], axis=1)

array([30, 70])

In [31]:
#NumPy Comparision
n1 = np.array([10, 20, 30])
n2 = np.array([10, 30, 20])

np.equal(n1, n2)

array([ True, False, False])

In [32]:
np.array_equal(n1, n2)

False

In [33]:
np.array_equiv(n1, n2)

False

###Joining arrays

In [34]:
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50 ,60])

In [35]:
np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [36]:
np.hstack((n1, n2))

array([10, 20, 30, 40, 50, 60])

In [37]:
np.column_stack((n1, n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

###Manipulating

In [38]:
n1

array([10, 20, 30])

In [40]:
n1 = n1/2
n1

array([ 5., 10., 15.])

In [41]:
n1 = n1 + 1
n1

array([ 6., 11., 16.])

In [42]:
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])

In [43]:
np.intersect1d(n1, n2)

array([50, 60])

In [44]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [45]:
n1 = np.random.randint(1, 100, 6)
n1

array([91,  9, 89, 60, 97, 20])

In [46]:
np.std(n1)

35.03807452852777

In [47]:
np.mean(n1)

61.0

In [48]:
np.median(n1)

74.5